/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
    public double divide(int a, int b){
    	if(b ==0) {
    		throw new IllegalArgumentException("Division par 0 impossible");
    	}
		return (double) a/b;
    }
}
